logging:
  level:
    '[org.springframework.web]': debug
    '[org.springframework.jdbc.datasource]': debug
  file: logs/petclinic.log

#Log seviyeleri
#OFF
#FATAL
#ERROR
#WARN
#INFO
#DEBUG
#TRACE
 

 